import React, { useState } from 'react';
import { Heart, ShieldCheck, Lock, MessageSquareText, ArrowRight } from 'lucide-react';
interface PixDonationCardProps { onSuccess?: () => void; compact?: boolean; }
export const PixDonationCard: React.FC<PixDonationCardProps> = ({ compact = false }) => {
 const [amount,setAmount]=useState(25),[customAmount,setCustomAmount]=useState(''),[message,setMessage]=useState(''),[donorName,setDonorName]=useState(''),[donorEmail,setDonorEmail]=useState(''),[leaveMessage,setLeaveMessage]=useState(false),[submitting,setSubmitting]=useState(false),[error,setError]=useState('');
 const selectedValue=customAmount.trim()?Number(customAmount.replace(',','.')):amount;
 const startDonation=async()=>{
  setError('');
  if(!Number.isFinite(selectedValue)||selectedValue<5||selectedValue>10000){setError('Escolha um valor entre R$ 5,00 e R$ 10.000,00.');return;}
  if(donorEmail.trim()&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(donorEmail.trim())){setError('Informe um e-mail válido ou deixe o campo vazio.');return;}
  if(leaveMessage&&message.trim().length<3){setError('Escreva uma mensagem curta ou desmarque essa opção.');return;}
  setSubmitting(true);
  try{
   const response=await fetch('/api/donation',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({amount:Math.round(selectedValue*100)/100,donorName:donorName.trim(),donorEmail:donorEmail.trim().toLowerCase(),message:leaveMessage?message.trim():''})});
   const result=await response.json();
   if(!response.ok){setError(result.message||'Não foi possível iniciar a doação. Tente novamente.');return;}
   if(typeof result.checkoutUrl!=='string'||!result.checkoutUrl.startsWith('https://')){setError('O provedor não retornou um endereço seguro de pagamento.');return;}
   window.location.assign(result.checkoutUrl);
  }catch{setError('Não foi possível conectar ao serviço de pagamento. Tente novamente.');}finally{setSubmitting(false);}
 };
 return <section className={`bg-white rounded-2xl border border-[#D9DEE7] shadow-sm overflow-hidden ${compact?'p-5':'p-6 md:p-8'}`}>
  <div className="flex items-start gap-3 border-b border-[#E5E7EB] pb-5"><div className="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl bg-rose-50 text-rose-600"><Heart size={22}/></div><div><h3 className="font-serif text-xl font-black text-[#0B2345]">Apoie O Patriota</h3><p className="mt-1 text-sm leading-6 text-[#5D6673]">Sua contribuição voluntária ajuda a manter o jornalismo independente. Escolha o valor e conclua o pagamento em ambiente seguro.</p></div></div>
  <div className="mt-5"><label className="mb-2 block text-xs font-bold uppercase tracking-wide text-[#0B2345]">Valor da contribuição</label><div className="grid grid-cols-2 gap-2 sm:grid-cols-4">{[10,25,50,100].map(v=><button key={v} type="button" onClick={()=>{setAmount(v);setCustomAmount('');}} className={`rounded-xl border px-3 py-3 text-sm font-extrabold ${!customAmount&&amount===v?'border-[#0B5FFF] bg-blue-50 text-[#0B2345]':'border-[#D9DEE7] bg-white text-[#344054] hover:border-[#0B5FFF]'}`}>R$ {v.toLocaleString('pt-BR',{minimumFractionDigits:2})}</button>)}</div><label htmlFor="donation-custom-amount" className="mb-1 mt-3 block text-xs font-semibold text-[#5D6673]">Outro valor (mínimo R$ 5,00)</label><div className="flex items-center gap-2"><span className="text-sm font-bold text-[#344054]">R$</span><input id="donation-custom-amount" inputMode="decimal" value={customAmount} onChange={e=>setCustomAmount(e.target.value)} placeholder="Digite o valor" className="min-h-11 w-full rounded-lg border border-[#D9DEE7] px-3 text-sm outline-none focus:border-[#0B5FFF]"/></div></div>
  <div className="mt-5 grid gap-3 sm:grid-cols-2"><div><label htmlFor="donor-name" className="mb-1 block text-xs font-semibold text-[#344054]">Nome (opcional)</label><input id="donor-name" value={donorName} maxLength={120} onChange={e=>setDonorName(e.target.value)} placeholder="Como podemos chamar você?" className="min-h-11 w-full rounded-lg border border-[#D9DEE7] px-3 text-sm outline-none focus:border-[#0B5FFF]"/></div><div><label htmlFor="donor-email" className="mb-1 block text-xs font-semibold text-[#344054]">E-mail (opcional)</label><input id="donor-email" type="email" value={donorEmail} maxLength={254} onChange={e=>setDonorEmail(e.target.value)} placeholder="Para contato sobre a doação" className="min-h-11 w-full rounded-lg border border-[#D9DEE7] px-3 text-sm outline-none focus:border-[#0B5FFF]"/></div></div>
  <div className="mt-5 rounded-xl border border-[#D9DEE7] bg-[#F8FAFC] p-4"><label className="flex cursor-pointer items-start gap-3"><input type="checkbox" checked={leaveMessage} onChange={e=>setLeaveMessage(e.target.checked)} className="mt-1 h-4 w-4 accent-[#0B5FFF]"/><span><span className="flex items-center gap-2 text-sm font-bold text-[#0B2345]"><MessageSquareText size={17}/>Deseja deixar uma mensagem para nossa equipe avaliar?</span><span className="mt-1 block text-xs leading-5 text-[#5D6673]">Opcional. A mensagem será encaminhada para análise da equipe e não será publicada automaticamente.</span></span></label>{leaveMessage&&<div className="mt-3"><label htmlFor="donation-message" className="mb-1 block text-xs font-semibold text-[#344054]">Sua mensagem</label><textarea id="donation-message" value={message} onChange={e=>setMessage(e.target.value)} maxLength={500} rows={4} placeholder="Escreva sua mensagem, sugestão ou comentário (até 500 caracteres)." className="w-full resize-y rounded-lg border border-[#D9DEE7] bg-white p-3 text-sm leading-5 outline-none focus:border-[#0B5FFF]"/><div className="mt-1 text-right text-[11px] text-[#718096]">{message.length}/500</div></div>}</div>
  {error&&<p role="alert" className="mt-4 rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-red-800">{error}</p>}
  <button type="button" onClick={startDonation} disabled={submitting} className="mt-5 flex min-h-12 w-full items-center justify-center gap-2 rounded-xl bg-[#0B2345] px-4 py-3 text-sm font-extrabold text-white transition hover:bg-[#0B5FFF] disabled:cursor-wait disabled:opacity-60"><Heart size={17}/>{submitting?'Preparando contribuição…':`Contribuir R$ ${Number.isFinite(selectedValue)?selectedValue.toLocaleString('pt-BR',{minimumFractionDigits:2,maximumFractionDigits:2}):'0,00'}`}<ArrowRight size={17}/></button>
  <div className="mt-4 flex items-start gap-2 text-[11px] leading-5 text-[#5D6673]"><ShieldCheck size={16} className="mt-0.5 shrink-0 text-[#16803C]"/><span>Pagamento processado pelo provedor. A mensagem é opcional, privada por padrão e sujeita à avaliação da equipe. Não informe dados financeiros ou informações pessoais sensíveis.</span></div><div className="mt-2 flex items-center gap-1.5 text-[11px] text-[#718096]"><Lock size={13}/>Seus dados de pagamento não são digitados neste formulário.</div>
 </section>;
};
